"""Test django settings."""
DEBUG = True
USE_I18N = True
LANGUAGE_CODE = 'en'
DEFAULT_TABLESPACE = None
DATABASES = {}
TRANSACTIONS_MANAGED = None
USE_TZ = None
DEFAULT_INDEX_TABLESPACE = None
ABSOLUTE_URL_OVERRIDES = {}
INSTALLED_APPS = []
SECRET_KEY = None
LOCALE_PATHS = []
LOGGING_CONFIG = None
LOGGING = None
EMAIL_BACKEND = None
ALLOWED_HOSTS = []
DATABASE_ENGINE = None
DATABASE_HOST = None
DATABASE_NAME = None
DATABASE_OPTIONS = None
DATABASE_PASSWORD = None
DATABASE_PORT = None
DATABASE_USER = None
TEST_DATABASE_CHARSET = None
TEST_DATABASE_COLLATION = None
TEST_DATABASE_NAME = None
DATABASE_ROUTERS = {}
TIME_ZONE = None
URL_VALIDATOR_USER_AGENT = None
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/var/tmp',
    }
}
